name: Code Quality Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.9
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run black --diff --check $(git ls-files '*.py')
      - run: poetry run pylint $(git ls-files '*.py') --rcfile=.pylintrc
      - run: poetry run mypy --strict $(git ls-files '*.py')
