name: Quality Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.9
      - uses: abatilo/actions-poetry@v2
        run: poetry install # Hack for mypy and pylint, don't want to run as system
      - uses: pre-commit/action@v3.0.0
