name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    permissions:
      pull-requests: read
      pull-request-reason: to get commits in pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
