name: Lint Commit Messages
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  commitlint:
    permissions:
      pull-requests: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
